### ISSUE TITLE
An error occurred on the first run

### ISSUE THREAD

**Issue by wangtianrui** [RoyJames/pygsound#4]
I'm really sorry to disturb you in your busy schedule. I follow your tutorial to operate, but I encounter some problems. I hope you can spare some time to give me some advice.Thank you very much!

sudo apt-get update
sudo apt-get -y install cmake python3-dev gobjc++ libfftw3-dev
Both steps have been completed！

(python3) root@iZ2zeab8t820b30ezwjthjZ:~/pygsound# python3 setup.py develop
running develop
running egg_info
writing src/pygsound.egg-info/PKG-INFO
writing requirements to src/pygsound.egg-info/requires.txt
writing dependency_links to src/pygsound.egg-info/dependency_links.txt
writing top-level names to src/pygsound.egg-info/top_level.txt
reading manifest file 'src/pygsound.egg-info/SOURCES.txt'
writing manifest file 'src/pygsound.egg-info/SOURCES.txt'
running build_ext
CMake Error at /opt/cmake-3.14.5-Linux-x86_64/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
Call Stack (most recent call first):
  /opt/cmake-3.14.5-Linux-x86_64/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /opt/cmake-3.14.5-Linux-x86_64/share/cmake-3.14/Modules/FindPkgConfig.cmake:41 (find_package_handle_standard_args)
  CMakeLists.txt:22 (find_package)

-- Configuring incomplete, errors occurred!
See also "/root/pygsound/build/temp.linux-x86_64-3.5/CMakeFiles/CMakeOutput.log".
See also "/root/pygsound/build/temp.linux-x86_64-3.5/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "setup.py", line 91, in <module>
    'wavefile',
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/setuptools/command/develop.py", line 38, in run
    self.install_for_development()
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/setuptools/command/develop.py", line 140, in install_for_development
    self.run_command('build_ext')
  File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 36, in run
    self.build_extension(ext)
  File "setup.py", line 65, in build_extension
    cwd=self.build_temp, env=env)
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/root/pygsound', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/root/pygsound/src/pygsound', '-DPYTHON_EXECUTABLE=/root/.virtualenvs/python3/bin/python3', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1
————————————————————————————————————————————————
environment：
cmake 3.14.5
python 3.5.2
Linux iZ2zeab8t820b30ezwjthjZ 4.4.0-151-generic #178-Ubuntu SMP Tue Jun 11 08:30:22 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by wangtianrui** [comment]
I'm sorry, it was my fault, and I've fixed it
